BEGIN;

ALTER TABLE IF EXISTS "package"
ADD "request_time" TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE IF EXISTS "package"
ADD "expedition_time" TIMESTAMPTZ;

ALTER TABLE IF EXISTS "package"
ADD "delivered_time" TIMESTAMPTZ;

COMMIT;