BEGIN;

ALTER TABLE IF EXISTS "package"
RENAME COLUMN "volume" TO "height";

ALTER TABLE IF EXISTS "package"
ADD "width" INT NOT NULL DEFAULT 1;

ALTER TABLE IF EXISTS "package"
ADD "depth" INT NOT NULL DEFAULT 1;

ALTER TABLE IF EXISTS "package"
ALTER COLUMN "width" DROP DEFAULT; --/remove default for future entries

ALTER TABLE IF EXISTS "package"
ALTER COLUMN "depth" DROP DEFAULT;

COMMIT;